apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chatbot-manual-testing-llama-custom 
  janus-idp.io/tekton: chatbot-manual-testing-llama-custom
  backstage.io/kubernetes-id: chatbot-manual-testing-llama-custom
  backstage.io/kubernetes-namespace: my-namespace-2 
  app.kubernetes.io/part-of: chatbot-manual-testing-llama-custom
resources: 
- application-dev.yaml