kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chatbot-manual-testing-llama-custom-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: chatbot-manual-testing-llama-custom-dsp-job
    namespace: my-namespace-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chatbot-manual-testing-llama-custom-dsp-job-role