apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-manual-testing-llama-custom
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/chatbot-manual-testing-llama-custom:8ea8abc0596eb019fb249832302a5b72787f333b@sha256:39b4c22c4c5eaeae8afaa08f74eb96f28192a36c36c4f7b6eb8db1e32d9c7d4b # use pre-built to bootstrap 
          name: app-inference
