---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-manual-testing-llama-custom
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-manual-testing-llama-custom 
  name: chatbot-manual-testing-llama-custom
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi